[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = '0.8.28'

via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.quick]
verbosity = 3
optimizer_runs = 1

[profile.perf]
verbosity = 3
optimizer = true
optimizer_runs = 10_000

[profile.perf.fuzz]
runs = 10_000